Document: udr
Title: Debian udr Manual
Author: <insert document author here>
Abstract: This manual describes what udr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/udr/udr.sgml.gz

Format: postscript
Files: /usr/share/doc/udr/udr.ps.gz

Format: text
Files: /usr/share/doc/udr/udr.text.gz

Format: HTML
Index: /usr/share/doc/udr/html/index.html
Files: /usr/share/doc/udr/html/*.html
